version: "3"

services:
  import:
    build:
      context: .
      dockerfile: Dockerfile_import
    volumes:
      - ./config_docker:/usr/src/app/config
    environment:
      - CONF=${CONFIG_FILE}
  download:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - import
    volumes:
      - ${DOWNLOAD_VOLUME}:/usr/src/app/WARC
      - ./config_docker:/usr/src/app/config
    environment:
      - CONF=${CONFIG_FILE}
      - ENGINE=${ENGINE}
